# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pets',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterField(
            model_name='pets',
            name='birthday',
            field=models.DateField(),
        ),
    ]
